INSERT INTO category (description) values ('American');
INSERT INTO category (description) values ('Itailian');
INSERT INTO category (description) values ('Mexican');
INSERT INTO category (description) values ('Fast food');
INSERT INTO unit_of_measure (name) values ('Teaspoon');
INSERT INTO unit_of_measure (name) values ('Tablespoon');
INSERT INTO unit_of_measure (name) values ('Cup');
INSERT INTO unit_of_measure (name) values ('Pinch');
INSERT INTO unit_of_measure (name) values ('Ounce');
INSERT INTO unit_of_measure (name) values ('Clove');
INSERT INTO unit_of_measure (name) values ('Quantity');
INSERT INTO unit_of_measure (name) values ('Pint');
